name: Terraform GitHub Actions
on:
  - push
jobs:
  format:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.15.0
      - name: Terraform Format
        run: terraform fmt -check -recursive
  validate:
    name: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - athene2_dbdump
          - athene2_dbsetup
          - athene2_metrics
          - dbdump
          - editor-renderer
          - legacy-editor-renderer
          - server
          - .
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.15.0
      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ${{ matrix.module }}
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.module }}
